apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-edu-service #set your name + -service
spec:
  selector:
    app: springboot-k8s-edu #set your application name
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
